directory = "_maps/sewercity/"


[rooms.sewerleft]
modules = ["sewer_left_ten_box.dmm", "sewer_left_ten_forcefield.dmm", "sewer_left_ten_kitchen.dmm", "sewer_left_ten_locked.dmm", "sewer_left_ten_medical.dmm", "sewer_left_ten_mining.dmm", "sewer_left_ten_poisoncrab.dmm", "sewer_left_ten_radiation.dmm", "sewer_left_ten_weaponcraft.dmm", "sewer_left_ten_zombie1.dmm", "sewer_left_ten_zombine1.dmm", "sewer_left_ten_coughers.dmm"]

[rooms.sewerright]
modules = ["sewer_right_ten_armory.dmm", "sewer_right_ten_box.dmm", "sewer_right_ten_doors.dmm", "sewer_right_ten_factory.dmm", "sewer_right_ten_fishing.dmm", "sewer_right_ten_flooded.dmm", "sewer_right_ten_headcrabs.dmm", "sewer_right_ten_headcrabs2.dmm", "sewer_right_ten_infested1.dmm", "sewer_right_ten_infested2.dmm"]

[rooms.citynorth]
modules = ["city_north_ten_niceapartment.dmm", "city_north_ten_store.dmm", "city_north_ten_store2.dmm", "city_north_ten_workshop.dmm", "city_north_ten_dorms.dmm", "city_north_ten_apartment.dmm"]

[rooms.citysouth]
modules = ["city_south_ten_gambling.dmm", "city_south_ten_laundromat.dmm", "city_south_ten_lockedapartment.dmm", "city_south_ten_oldapartment.dmm", "city_south_ten_hiddenworkshop.dmm"]

[rooms.outlandsbunkerwest]
modules = ["bunker_west_twenty_zombie.dmm", "bunker_west_twenty_comms.dmm"]

[rooms.miningcaves]
modules = ["cave_mining_headcrabs.dmm", "cave_mining_pillar.dmm", "cave_mining_grubs.dmm", "cave_mining_infestation.dmm", "cave_mining_antlions.dmm"]

[rooms.deploymentnorth]
modules = ["deployment_north_safehouse.dmm", "deployment_north_zombines.dmm", "deployment_north_fungalvault.dmm", "deployment_north_clinic.dmm", "deployment_north_shop.dmm", "deployment_north_industrial.dmm", "deployment_north_poisonzombies.dmm", "deployment_north_apartment.dmm"]

[rooms.deploymentsouth]
modules = ["deployment_south_safehouse.dmm", "deployment_south_zombines.dmm", "deployment_south_fungalvault.dmm", "deployment_south_clinic.dmm", "deployment_south_shop.dmm", "deployment_south_industrial.dmm", "deployment_south_poisonzombies.dmm", "deployment_north_apartment.dmm"]
